/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore;

/**
 *
 * @author ckopp
 */
public class MainForm extends javax.swing.JFrame {

    private final BookStore bookstore;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.bookstore = new BookStore();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newAuthorButton = new javax.swing.JButton();
        editAuthorButton = new javax.swing.JButton();
        linkTitleAuthorButton = new javax.swing.JButton();
        newTitleButton = new javax.swing.JButton();
        customQuery = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newAuthorButton.setText("Add new Author");
        newAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAuthorButtonActionPerformed(evt);
            }
        });

        editAuthorButton.setText("Edit Author Information");
        editAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAuthorButtonActionPerformed(evt);
            }
        });

        linkTitleAuthorButton.setText("Link existing Title to Existing Author");
        linkTitleAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkTitleAuthorButtonActionPerformed(evt);
            }
        });

        newTitleButton.setText("Add new Title");
        newTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTitleButtonActionPerformed(evt);
            }
        });

        customQuery.setText("Customer Query");
        customQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customQueryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editAuthorButton)
                    .addComponent(newAuthorButton)
                    .addComponent(linkTitleAuthorButton)
                    .addComponent(newTitleButton)
                    .addComponent(customQuery))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newTitleButton)
                .addGap(18, 18, 18)
                .addComponent(newAuthorButton)
                .addGap(18, 18, 18)
                .addComponent(editAuthorButton)
                .addGap(18, 18, 18)
                .addComponent(linkTitleAuthorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(customQuery)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAuthorButtonActionPerformed
        // TODO add your handling code here:
        this.bookstore.newAuthor();
    }//GEN-LAST:event_newAuthorButtonActionPerformed

    private void editAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAuthorButtonActionPerformed
        // TODO add your handling code here:
        this.bookstore.editAuthor();
    }//GEN-LAST:event_editAuthorButtonActionPerformed

    private void linkTitleAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkTitleAuthorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkTitleAuthorButtonActionPerformed

    private void newTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTitleButtonActionPerformed
        // TODO add your handling code here:
        this.bookstore.newTitle();
    }//GEN-LAST:event_newTitleButtonActionPerformed

    private void customQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customQueryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customQueryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customQuery;
    private javax.swing.JButton editAuthorButton;
    private javax.swing.JButton linkTitleAuthorButton;
    private javax.swing.JButton newAuthorButton;
    private javax.swing.JButton newTitleButton;
    // End of variables declaration//GEN-END:variables
}
